[package]
name = "zxc_write"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = {version = "0.62.2", features  = [
        "Win32_Foundation",
        "Win32_System_Threading",
        "Win32_System_Diagnostics_ToolHelp",
        "Win32_UI_WindowsAndMessaging",
        "Win32_System_Memory",
        "Win32_System_Diagnostics_Debug",
        "Win32_Security",
        "Win32_System_LibraryLoader",
        "Win32_Security_Authorization",
        "Win32_System_ProcessStatus",
    ]

}
vec-string = {git = "https://github.com/Utishnik/vec-string"}
threadpool = "1.8.1"
aes-gcm = "0.10.3"
getrandom = "0.3"
crossfire = "3.1.7"
chrono = "0.4.44"
ansi_term = "0.12.1"
mimalloc = {version = "0.1.50", features = ["secure"] }
#rimalloc = {git = "https://github.com/moggedhedien/rimalloc"}
hotpath = "0.16.1"
typed-arena = "2.0.2"
allocative = "0.3.6"
memchr = "2.8.1"

[features]
hotpath = ["hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
